#! /bin/sh -f

#$ -q long
#$ -N henry'sconstant 

export RASPA_DIR=${HOME}/Research/simulations/
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib
$RASPA_DIR/bin/simulate -i simulation.input
